export const INDEXED_DB_CONFIG = {
  DB_NAME: "ebonite",
  STORES: {
    STATUS_STORE: "ebonite_status",
    CATEGORIES_STORE: "ebonite_categories",
    USER_STORE: "ebonite_user",
  },
};

export const ROUTES = {
  LOGIN: { TITLE: "Login", PATH: "/login" },
  DASHBOARD: { TITLE: "Dashboard", PATH: "/dashboard" },
  PROJECTS: { TITLE: "Projects", PATH: "/projects" },
  CREATE_PROJECTS: { TITLE: "Create Project", PATH: "/projects/create" },
  VIEW_PROJECTS: { TITLE: "View Project", PATH: "/projects/view/:id" },
  NOTIFICATION: { TITLE: "Notification", PATH: "/notification" },
  GANTT: { TITLE: "Gantt Chart", PATH: "/gantt" },
  CALENDER: { TITLE: "Calender", PATH: "/calender" },
  FILES: { TITLE: "Files", PATH: "/files" },
  OLDER_FILES: { TITLE: "Older FIles", PATH: "/files/older/version" },
  CHAT: { TITLE: "Chat", PATH: "/chat" },
  TASK: { TITLE: "Task", PATH: "/task" },
  TASK_DETAILS: { TITLE: "Task Details", PATH: "/task/details" },
  SNAG_DETAILS: { TITLE: "Snag Details", PATH: "/snag/details" },
  VIOLATION_DETAILS: { TITLE: "Violation Details", PATH: "/violation/details" },
  ROLE: { TITLE: "Manage Role", PATH: "/role" },
  PERMISSION: { TITLE: "Permission", PATH: "/permission" },
  USER: { TITLE: "Manage User", PATH: "/user" },
  REDIRECT: { TITLE: "Gantt Redirect", PATH: "/gantt-redirect" },
};

export const COMPANY = {
  NAME: "Innobayt",
  LOGO: "/assets/images/common/logo.svg",
  FILTER: "/assets/images/common/filter.svg",
};

export const TITLE = {
  PROFILE: "Profile",
  LOGOUT: "Log out",
};

export const NOTIFICATION_TYPES = {
  CREATE_TASK: "CREATE_TASK",
  ASSIGN_TASK: "ASSIGN_TASK",
  TASK_PRIORITY_UPDATE: "TASK_PRIORITY_UPDATE",
  TASK_STATUS_UPDATE: "TASK_STATUS_UPDATE",
  TASK_COMPLETE_STATUS_UPDATE: "TASK_COMPLETE_STATUS_UPDATE",

  CREATE_SNAG: "CREATE_SNAG",
  ASSIGN_SNAG: "ASSIGN_SNAG",
  SNAG_PRIORITY_UPDATE: "SNAG_PRIORITY_UPDATE",
  SNAG_STATUS_UPDATE: "SNAG_STATUS_UPDATE",
  SNAG_COMPLETE_STATUS_UPDATE: "SNAG_COMPLETE_STATUS_UPDATE",

  CREATE_VIOLATION: "CREATE_VIOLATION",
  ASSIGN_VIOLATION: "ASSIGN_VIOLATION",
  CREATE_PROJECT: "CREATE_PROJECT",
  MENTIONED: "MENTIONED",
};

export const DATE_FORMAT = "YYYY-MM-DD";
export const TIME_FORMAT = "HH:mm";
export const ICONS = {
  DASHBOARD: "/assets/images/icons/dashboard.svg",
  LOGOUT: "/assets/images/icons/logout.svg",
  NOTIFICATION: "/assets/images/icons/notification.svg",
  PROJECTS: "/assets/images/icons/projects.svg",
  TASK: "/assets/images/icons/task.svg",
  SNAG: "/assets/images/icons/snag.svg",
  VIOLATION: "/assets/images/icons/violation.svg",
  MESSAGE: "/assets/images/icons/message.svg",
  DUE: "/assets/images/icons/due.svg",
  PRIORITY: "/assets/images/icons/priority.svg",
  TYPE: "/assets/images/icons/type.svg",
  TYPE: "/assets/images/icons/type.svg",
  CATEGORY: "/assets/images/icons/category.svg",
  PDF: "/assets/images/icons/pdf.png",
  SUBTASK: "/assets/images/icons/board-task-icon.svg",
  CHECKED_FOLDER: "/assets/images/icons/checkedFolders.png",
  IMAGE: "/assets/images/icons/image.png",
  FILE: "/assets/images/icons/file.png",
};

export const SOCKET_EVENT_NAME = {
  SOCKET_ACK: "socket_ack",
  SEND_NEW_MESSAGE: "send-new-message",
  NEW_MESSAGE_ACK: "new-message-ack",
  GET_MESSAGE: "get-message",
  EDIT_MESSAGE: "edit-message",
  MESSAGE_EDITED: "message-edited",
  EDIT_MESSAGE_ACK: "edit-message-ack",
  DELETE_MESSAGE: "delete-message",
  DELETE_MESSAGE_ACK: "delete-message-ack",
  MESSAGE_DELETED: "message-deleted",
  USER_LIST: "get-user-list",
  USER_LIST_RESP: "user-list",
  CHAT_LISTING: "chat-listing",
  CHAT_LISTING_RESP: "chat-listing-resp",
  ERROR: "exception",
  DISCONNECTED: "disconnect",
  NEW_MESSAGE: "new-message",
  RECEIVED_MESSAGES: "received-messages",
  SEEN_MESSAGES: "seen-messages",
  MESSAGE_UPDATED: "message-updated",
  USER_STATUS: "user-status",
  USER_STATUS_RESP: "user-status-resp",
  RECENT_CHAT_USER: "recent-chat-user",
  REFRESH: "refresh",
};

export const TASK_FORM = {
  PHASE: {
    LABEL: "Phase",
    PLACEHOLDER: "Phase",
    NAME: "phase",
    KEY: "phase",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select the phase",
  },
  CATEGORY: {
    LABEL: "Category",
    PLACEHOLDER: "Category",
    NAME: "category",
    KEY: "category",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select the category",
  },
  SUMMARY: {
    LABEL: "Summary",
    PLACEHOLDER: "Summary",
    NAME: "summary",
    KEY: "summary",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter the summary",
  },
  PRIORITY: {
    LABEL: "Priority",
    PLACEHOLDER: "Priority",
    NAME: "priority",
    KEY: "priority",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select the priority",
  },
  DESCRIPTION: {
    LABEL: "Description",
    PLACEHOLDER: "Description",
    NAME: "description",
    KEY: "description",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter the description",
  },
  ASSIGNEE: {
    LABEL: "Assignee",
    PLACEHOLDER: "Assignee",
    NAME: "assignee",
    KEY: "assignee",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select the assignee",
  },
  START_DATE: {
    LABEL: "Start Date",
    PLACEHOLDER: "Start Date",
    NAME: "task_start_date",
    KEY: "task_start_date",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select start date.",
  },
  END_DATE: {
    LABEL: "End Date",
    PLACEHOLDER: "End Date",
    NAME: "task_end_date",
    KEY: "task_end_date",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select due date.",
  },
  NO_OF_DAYS: {
    LABEL: "Number of days",
    PLACEHOLDER: "Number of days",
    NAME: "number_of_days",
    KEY: "number_of_days",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter number of days",
  },
};

export const SNAG_FORM = {
  CATEGORY: {
    LABEL: "Category",
    PLACEHOLDER: "Category",
    NAME: "category",
    KEY: "category",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select the category",
  },
  SUMMARY: {
    LABEL: "Summary",
    PLACEHOLDER: "Summary",
    NAME: "summary",
    KEY: "summary",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter the summary",
  },
  PRIORITY: {
    LABEL: "Priority",
    PLACEHOLDER: "Priority",
    NAME: "priority",
    KEY: "priority",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select the priority",
  },
  DESCRIPTION: {
    LABEL: "Description",
    PLACEHOLDER: "Description",
    NAME: "description",
    KEY: "description",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter the description",
  },
  ASSIGNEE: {
    LABEL: "Assignee",
    PLACEHOLDER: "Assignee",
    NAME: "assignee",
    KEY: "assignee",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select the assignee",
  },
  START_DATE: {
    LABEL: "Start Date",
    PLACEHOLDER: "Start Date",
    NAME: "start_date",
    KEY: "start_date",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select start date.",
  },
  DUE_DATE: {
    LABEL: "Due Date",
    PLACEHOLDER: "Due Date",
    NAME: "due_date",
    KEY: "due_date",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select due date.",
  },
  NO_OF_DAYS: {
    LABEL: "Number of days",
    PLACEHOLDER: "Number of days",
    NAME: "number_of_days",
    KEY: "number_of_days",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter number of days",
  },
};

export const VIOLATION_FORM = {
  DESCRIPTION: {
    LABEL: "Description",
    PLACEHOLDER: "Description",
    NAME: "description",
    KEY: "description",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter the description.",
  },
  REPORT_NO: {
    LABEL: "Report No",
    PLACEHOLDER: "Report No",
    NAME: "report_no",
    KEY: "report_no",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter the report number.",
  },
  VIOLATION_DATE: {
    LABEL: "Date",
    PLACEHOLDER: "Date",
    NAME: "violation_date",
    KEY: "violation_date",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select date-time",
  },
  LOCATION: {
    LABEL: "Location",
    PLACEHOLDER: "Location",
    NAME: "location",
    KEY: "location",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter the location.",
  },
  COMPANY_NAME: {
    LABEL: "Company name",
    PLACEHOLDER: "Company name",
    NAME: "company_name",
    KEY: "company_name",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter the company name.",
  },
  NAME_OF_VIOLATOR: {
    LABEL: "Name of Violator",
    PLACEHOLDER: "Name of Violator",
    NAME: "name_of_violator",
    KEY: "name_of_violator",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter the name of violator.",
  },
  ID_NUMBER: {
    LABEL: "ID Number",
    PLACEHOLDER: "ID Number",
    NAME: "id_number",
    KEY: "id_number",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter the id number",
  },
  WARNING_NO: {
    LABEL: "Warning Number",
    PLACEHOLDER: "Warning Number",
    NAME: "warning_number",
    KEY: "warning_number",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter the warning number",
  },
  ACTION_SUGGESTED_BY: {
    LABEL: "Action Suggested By",
    PLACEHOLDER: "Action Suggested By",
    NAME: "action_suggested_by",
    KEY: "action_suggested_by",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select action suggested by",
  },
  VIOLATION_CATEGORY: {
    LABEL: "Violation Category",
    PLACEHOLDER: "Violation Category",
    NAME: "violation_category",
    KEY: "violation_category",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select violation category",
  },
  VIOLATION_CATEGORY_DATA: {
    LABEL: "Violation Category Data",
    PLACEHOLDER: "Violation Data",
    NAME: "violation_category_data",
    KEY: "violation_category_data",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter violation category data",
  },
  PREPARED_BY: {
    LABEL: "Prepared By",
    PLACEHOLDER: "Prepared By",
    NAME: "prepared_by",
    KEY: "prepared_by",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select prepared by",
  },
  APPROVED_BY: {
    LABEL: "Approved By",
    PLACEHOLDER: "Approved By",
    NAME: "approved_by",
    KEY: "approved_by",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select Approved By",
  },
};

export const PROJECT_FORM = {
  PROJECT_NUMBER: {
    LABEL: "Project Number",
    PLACEHOLDER: "Project Number",
    NAME: "project_number",
    KEY: "project_number",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter the project number.",
    MAX: 30,
  },
  PROJECT_NAME: {
    LABEL: "Project Name",
    PLACEHOLDER: "Project Name",
    NAME: "project_name",
    KEY: "project_name",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter the project name.",
    MAX: 50,
  },
  CATEGORY: {
    LABEL: "Category",
    PLACEHOLDER: "Select Category",
    NAME: "category",
    KEY: "category",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select the category.",
  },
  MEP_MANAGER: {
    LABEL: "MEP Manager",
    PLACEHOLDER: "Select MEP Manager",
    NAME: "mep_manager",
    KEY: "mep_manager",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select the mep manager.",
  },
  JOINERY_MANAGER: {
    LABEL: "Joinery Manager",
    PLACEHOLDER: "Select Joinery Manager",
    NAME: "joinery_manager",
    KEY: "joinery_manager",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select the joinery manager.",
  },

  START_DATE: {
    LABEL: "Start Date",
    PLACEHOLDER: "Start Date",
    NAME: "start_date",
    KEY: "start_date",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select date.",
  },
  END_DATE: {
    LABEL: "End Date",
    PLACEHOLDER: "End Date",
    NAME: "end_date",
    KEY: "end_date",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select date.",
  },
  NO_OF_DAYS: {
    LABEL: "No. of days",
    PLACEHOLDER: "No. of days",
    NAME: "number_of_days",
    KEY: "number_of_days",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter no of days",
  },
  DESCRIPTION: {
    LABEL: "Description",
    PLACEHOLDER: "Description",
    NAME: "description",
    KEY: "description",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter description",
    MAX: 250,
  },

  PROJECT_MANAGER: {
    LABEL: "Assign Project Manager",
    PLACEHOLDER: "Project Manager",
    NAME: "project_manager",
    KEY: "project_manager",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select project manager",
  },
  PROJECT_COORDINATOR: {
    LABEL: "Assign Project Coordinator",
    PLACEHOLDER: "Project Coordinator",
    NAME: "project_coordinator",
    KEY: "project_coordinator",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select project coordinator",
  },
  DEFAULT_TEAM_MEMBERS: {
    LABEL: "Default Team Members",
    PLACEHOLDER: "Default Team Members",
    NAME: "default_team_member",
    KEY: "default_team_member",
    REQUIRED: false,
  },
  PROJECT_TEAM_MEMBERS: {
    LABEL: "Team Members",
    PLACEHOLDER: "Select Team Members",
    NAME: "team_members",
    KEY: "team_members",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select team members",
  },
  MILESTONE: {
    LABEL: "Select Milestones",
    PLACEHOLDER: "Select Milestone",
    NAME: "is_percentage",
    KEY: "is_percentage",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select milestone option",
  },
  MILESTONE_NAME: {
    LABEL: "Milestone Name",
    PLACEHOLDER: "Milestone name",
    NAME: "milestone_name",
    KEY: "milestone_name",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter milestone name",
    MAX: 50,
  },
  MILESTONE_STATUS: {
    LABEL: "Milestone Status",
    PLACEHOLDER: "Milestone status",
    NAME: "milestone_status",
    KEY: "milestone_status",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter milestone status",
    MAX: 50,
  },
  MILESTONE_PERCENTAGE: {
    LABEL: "Milestone Percentage",
    PLACEHOLDER: "Milestone Percentage",
    NAME: "milestone_percentage",
    KEY: "milestone_percentage",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter milestone percentage",
  },
  EMAIL: {
    LABEL: "Email",
    PLACEHOLDER: "Enter Email",
    NAME: "email",
    KEY: "email",
    REQUIRED: false,
    ERROR_MESSAGE: "Please enter email",
    REGEX: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    MAX: 50,
  },
  PHASE: {
    LABEL: "Phase",
    PLACEHOLDER: "Enter phase",
    NAME: "phase",
    KEY: "phase",
    REQUIRED: false,
    ERROR_MESSAGE: "Please enter phase",
    MAX: 50,
  },
};

export const PROJECT_MEETING_FORM = {
  MEETING_NAME: {
    LABEL: "Meeting Name",
    PLACEHOLDER: "Meeting Name",
    NAME: "meeting_name",
    KEY: "meeting_name",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter the meeting name.",
    MAX: 30,
  },
  START_DATE: {
    LABEL: "Start Date",
    PLACEHOLDER: "Start Date",
    NAME: "start_date",
    KEY: "start_date",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select start date.",
  },
  END_DATE: {
    LABEL: "End Date",
    PLACEHOLDER: "End Date",
    NAME: "end_date",
    KEY: "end_date",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select end date.",
  },
  START_TIME: {
    LABEL: "Start time",
    PLACEHOLDER: "Start time",
    NAME: "start_time",
    KEY: "start_time",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select start time.",
  },
  END_TIME: {
    LABEL: "End time",
    PLACEHOLDER: "End time",
    NAME: "end_time",
    KEY: "end_time",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select end time.",
  },
  DESCRIPTION: {
    LABEL: "Description",
    PLACEHOLDER: "Description",
    NAME: "description",
    KEY: "description",
    REQUIRED: true,
    ERROR_MESSAGE: "Please enter the description.",
    MAX: 50,
  },
  RECURRENCE: {
    LABEL: "Recurrence",
    PLACEHOLDER: "Recurrence",
    NAME: "recurrence",
    KEY: "recurrence",
    REQUIRED: true,
    ERROR_MESSAGE: "Please select recurrence.",
  },
  RECURRENCE_RULE: {
    LABEL: "Weekly on",
    PLACEHOLDER: "Recurrence Rule",
    NAME: "recurrence_rule",
    KEY: "recurrence_rule",
    REQUIRED: false,
    ERROR_MESSAGE: "Please select recurrence rule.",
  },
};

export let DAYS_OF_WEEK = [
  { label: "Sunday", value: "0" },
  { label: "Monday", value: "1" },
  { label: "Tuesday", value: "2" },
  { label: "Wednesday", value: "3" },
  { label: "Thursday", value: "4" },
  { label: "Friday", value: "5" },
  { label: "Saturday", value: "6" },
];

export let RECURRENCE_TYPES = [
  "Do not repeat",
  "Repeat daily",
  "Repeat weekly",
  "Repeat monthly",
  "Repeat yearly",
  "Custom",
];

export let MEETING_MODEL_TITLE = [
  "Add Project Meeting",
  "Edit Project Meeting",
];

export const MILESTONE_OPTIONS = [
  {
    value: false,
    label: "Option 1",
  },
  {
    value: true,
    label: "Option 2",
  },
];
export const IP_URL = "https://api.ipify.org/?format=json";
